# Generated by Django 5.1.4 on 2025-01-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(default='foo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='application_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_questions', to='stave.applicationform'),
        ),
        migrations.AlterField(
            model_name='question',
            name='application_form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_questions', to='stave.applicationformtemplate'),
        ),
    ]
