# Generated by Django 5.1.4 on 2025-02-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0002_alter_rolegroupcrewassignment_crew"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolegroup",
            name="requires_profile_fields",
        ),
        migrations.AlterField(
            model_name="applicationform",
            name="application_kind",
            field=models.IntegerField(
                choices=[(1, "Confirm Only"), (2, "Confirm then Assign")]
            ),
        ),
        migrations.AlterField(
            model_name="applicationformtemplate",
            name="application_kind",
            field=models.IntegerField(
                choices=[(1, "Confirm Only"), (2, "Confirm then Assign")]
            ),
        ),
    ]
