# Generated by Django 5.1.4 on 2025-01-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0002_league_slug_question_content_question_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('allow_other', True), models.Q(('kind__exact', 4), _negated=True)), name='other_only_for_multi'),
        ),
    ]
