# Generated by Django 5.1.4 on 2025-01-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0003_question_other_only_for_multi'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='only_one_relation',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='other_only_for_multi',
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='requires_profile_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='applicationformtemplate',
            name='requires_profile_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='rolegroup',
            name='requires_profile_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('application_form_template__isnull', False), ('application_form__isnull', False), _connector='XOR'), name='exactly_one_relation'),
        ),
    ]
