# Generated by Django 5.1.4 on 2025-02-02 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0003_remove_rolegroup_requires_profile_fields_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewassignment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crews",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rolegroupcrewassignment",
            name="crew_overrides",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_group_override_assignments",
                to="stave.crew",
            ),
        ),
    ]
