# Generated by Django 5.1.4 on 2025-01-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0004_remove_question_only_one_relation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['role_group', 'order_key']},
        ),
        migrations.AddField(
            model_name='role',
            name='order_key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
