# Generated by Django 5.1.4 on 2025-01-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0005_alter_role_options_role_order_key_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('role_group', 'order_key'), name='unique_order_key'),
        ),
    ]
