# Generated by Django 5.1.4 on 2025-02-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0005_alter_applicationresponse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="league",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="league",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="applicationresponse",
            constraint=models.UniqueConstraint(
                fields=("application", "question"),
                name="one_response_per_question_per_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("application_form", "application_form_template", "order_key"),
                name="unique_question_order_key",
            ),
        ),
    ]
