# Generated by Django 5.1.4 on 2025-02-04 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0006_league_description_league_logo_league_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueuserrole",
            name="role",
            field=models.IntegerField(
                choices=[(1, "League Manager"), (2, "Event Manager")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leagueuserrole",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="stave.league",
            ),
        ),
        migrations.AlterField(
            model_name="leagueuserrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
