# Generated by Django 5.1.4 on 2025-01-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0007_alter_league_options_league_unique_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='Game', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='order_key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
