# Generated by Django 5.1.4 on 2025-01-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0008_game_name_game_order_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('event', 'order_key'), name='unique_order_key_event'),
        ),
    ]
