# Generated by Django 5.1.4 on 2025-02-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0008_leagueuserpermission_delete_leagueuserrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationform',
            options={'ordering': ['slug']},
        ),
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(help_text="The version of the league's name used in web addresses. Should be alphanumeric and contain no spaces, e.g., Central City Derby->central-city-derby"),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_history_url',
            field=models.URLField(blank=True, null=True, verbose_name='game history URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(max_length=256, verbose_name='preferred name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='pronouns'),
        ),
        migrations.AddConstraint(
            model_name='applicationform',
            constraint=models.UniqueConstraint(models.F('slug'), models.F('event'), name='no-duplicate-form-slugs', violation_error_message='Application form slugs must be unique for any given Event.'),
        ),
    ]
