# Generated by Django 5.1.4 on 2025-01-14 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0009_game_unique_order_key_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['order_key']},
        ),
        migrations.AlterField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='stave.event'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_forms', to='stave.event'),
        ),
        migrations.AlterField(
            model_name='applicationformtemplate',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_form_templates', to='stave.league'),
        ),
        migrations.AlterField(
            model_name='applicationresponse',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='stave.application'),
        ),
        migrations.AlterField(
            model_name='applicationresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='stave.question'),
        ),
        migrations.AlterField(
            model_name='eventrole',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_roles', to='stave.event'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='stave.league'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='stave.application'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stave.game'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stave.eventrole'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
