# Generated by Django 5.1.4 on 2025-02-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0010_league_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationform",
            name="close_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationform",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
