# Generated by Django 5.1.4 on 2025-01-14 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0010_alter_game_options_alter_application_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='stave.event'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='stave.rolegroup'),
        ),
    ]
