# Generated by Django 5.1.4 on 2025-01-15 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0011_alter_game_event_alter_role_role_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrole',
            name='event',
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stave.role'),
        ),
        migrations.RemoveConstraint(
            model_name='application',
            name='one_app_per_event_per_user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='role_structure',
        ),
        migrations.AddField(
            model_name='application',
            name='availability',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='stave.applicationform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='application_availability_kind',
            field=models.IntegerField(choices=[(1, 'Entire Event'), (2, 'By Day'), (3, 'By Game')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='role_groups',
            field=models.ManyToManyField(blank=True, to='stave.rolegroup'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='role_groups',
            field=models.ManyToManyField(blank=True, to='stave.rolegroup'),
        ),
        migrations.AddField(
            model_name='game',
            name='role_groups',
            field=models.ManyToManyField(blank=True, to='stave.rolegroup'),
        ),
        migrations.AddField(
            model_name='role',
            name='nonexclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='application_kind',
            field=models.IntegerField(choices=[(1, 'Confirm Only'), (2, 'Confirm then Assign'), (3, 'Direct Signup')]),
        ),
        migrations.AlterField(
            model_name='applicationformtemplate',
            name='application_kind',
            field=models.IntegerField(choices=[(1, 'Confirm Only'), (2, 'Confirm then Assign'), (3, 'Direct Signup')]),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('form', 'user'), name='one_app_per_event_per_user'),
        ),
        migrations.DeleteModel(
            name='EventRole',
        ),
    ]
