# Generated by Django 5.1.4 on 2025-03-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0013_remove_event_crew_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='is_override',
        ),
        migrations.AddField(
            model_name='crew',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Event Crew'), (2, 'Game Crew'), (3, 'Override Crew')], default=2),
        ),
    ]
