# Generated by Django 5.1.4 on 2025-03-04 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0015_crew_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolegroupcrewassignment",
            name="crew_overrides",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_group_override_assignments",
                to="stave.crew",
            ),
        ),
        migrations.AddConstraint(
            model_name="crewassignment",
            constraint=models.UniqueConstraint(
                fields=("crew", "role"), name="one_assignment_per_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="leagueuserpermission",
            constraint=models.UniqueConstraint(
                fields=("user", "league", "permission"), name="unique_grant"
            ),
        ),
    ]
