# Generated by Django 5.1.4 on 2025-03-05 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0016_alter_rolegroupcrewassignment_crew_overrides_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='rolegroup',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stave.league'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stave.league'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='league_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stave.leaguetemplate'),
        ),
        migrations.AddField(
            model_name='rolegroup',
            name='league_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stave.leaguetemplate'),
        ),
        migrations.AddConstraint(
            model_name='eventtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('league__isnull', True), ('league_template__isnull', True), _connector='XOR'), name='eventtemplate_either_league_or_league_template'),
        ),
        migrations.AddConstraint(
            model_name='rolegroup',
            constraint=models.CheckConstraint(condition=models.Q(('league__isnull', True), ('league_template__isnull', True), _connector='XOR'), name='either_league_or_league_template'),
        ),
    ]
