# Generated by Django 5.1.4 on 2025-03-13 17:05

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0017_leaguetemplate_rolegroup_league_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="event",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Drafting"),
                    (1, "Link Only"),
                    (2, "Open"),
                    (3, "In Progress"),
                    (4, "Complete"),
                    (5, "Canceled"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="nso_certification_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Recognized", "Recognized"),
                    ("Level 1", "Level 1"),
                    ("Level 2", "Level 2"),
                    ("Level 3", "Level 3"),
                ],
                max_length=32,
                null=True,
                verbose_name="NSO certification level",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="so_certification_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Recognized", "Recognized"),
                    ("Level 1", "Level 1"),
                    ("Level 2", "Level 2"),
                    ("Level 3", "Level 3"),
                ],
                max_length=32,
                null=True,
                verbose_name="SO certification level",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="wftda_insurance_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="WFTDA insurance number"
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="stave.league",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
