# Generated by Django 5.1.4 on 2025-03-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0018_alter_event_managers_event_status_league_enabled_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="event",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="legal_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
