# Generated by Django 5.1.4 on 2025-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0019_alter_event_managers_user_legal_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="league_affiliation",
            field=models.CharField(default="Independent", max_length=256),
        ),
    ]
