# Generated by Django 5.1.4 on 2025-03-14 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0020_user_league_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='invitation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='schedule_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='application_availability_kind',
            field=models.IntegerField(choices=[(1, 'Entire Event'), (2, 'By Day'), (3, 'By Game')], help_text='You can request availability at the level of the whole event, whole days, or by individual game. Single-game events must use Entire Event.', verbose_name='availability type'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='application_kind',
            field=models.IntegerField(choices=[(1, 'Confirm Only'), (2, 'Confirm then Assign')], help_text='Choose Confirm Only to contact applicants only once, when the schedule is finalized. Choose Confirm then Assign to send acceptance messages first, then follow with a schedule.', verbose_name='application process'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='hidden',
            field=models.BooleanField(default=False, help_text="Hidden forms are accessible only by direct link, and aren't listed on Stave."),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='intro_text',
            field=models.TextField(help_text="Introduce the event to your applicants. You don't need to include dates or locations, because these are recorded on the event already. You can use Markdown to format this text."),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='requires_profile_fields',
            field=models.JSONField(blank=True, default=list, help_text="You can accept standard fields from the user's profile without requiring them to re-type their information."),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='role_groups',
            field=models.ManyToManyField(help_text='The role groups covered by this form. You can select any or all of the role groups assigned to the event. Each role group can appear on only one form.', to='stave.rolegroup'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='slug',
            field=models.SlugField(help_text='Form name used in web addresses. Should be alphanumeric and contain no spaces, e.g., apply or apply-nso'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text="The version of the event's name used in web addresses. Should be alphanumeric and contain no spaces, e.g., Summer Throwdown->summer-throwdown"),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_plain_text', models.TextField()),
                ('content_html', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(null=True)),
                ('tries', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
