# Generated by Django 5.1.4 on 2025-03-17 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0023_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtemplate",
            name="league_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_templates",
                to="stave.leaguetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="gametemplate",
            name="event_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_templates",
                to="stave.eventtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="rolegroup",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_groups",
                to="stave.league",
            ),
        ),
        migrations.AlterField(
            model_name="rolegroup",
            name="league_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_groups",
                to="stave.leaguetemplate",
            ),
        ),
    ]
