# Generated by Django 5.1.4 on 2025-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0026_alter_eventtemplate_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtemplate",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
