# Generated by Django 5.1.4 on 2025-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0028_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
