# Generated by Django 5.1.4 on 2025-03-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0029_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
