# Generated by Django 5.1.4 on 2025-04-10 18:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0031_alter_rolegroupcrewassignment_crew_overrides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gametemplate",
            name="end_time",
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AlterField(
            model_name="gametemplate",
            name="start_time",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
