# Generated by Django 5.1.4 on 2025-04-17 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0034_gametemplate_association_gametemplate_home_league_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="role_groups",
            field=models.ManyToManyField(
                through="stave.RoleGroupCrewAssignment", to="stave.rolegroup"
            ),
        ),
        migrations.AlterField(
            model_name="rolegroupcrewassignment",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stave.game"
            ),
        ),
    ]
