# Generated by Django 5.1.4 on 2025-04-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0036_alter_rolegroupcrewassignment_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolegroup',
            name='event_only',
            field=models.BooleanField(default=False),
        ),
    ]
