# Generated by Django 5.1.4 on 2025-04-21 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0038_rename_decline_email_set_application_decline_email_sent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="decline_email_sent",
            new_name="rejection_email_sent",
        ),
    ]
