# Generated by Django 5.2.3 on 2025-07-20 14:52

from django.db import migrations, models


def convert_statuses(apps, schema_editor):
    Application = apps.get_model("stave", "Application")
    for application in Application.objects.all():
        if (
            application.status == 2  # ApplicationStatus.INVITED
            and not application.invitation_email_sent
        ):
            application.status = 7  # ApplicationStatus.INVITATION_PENDING
            application.save()
        elif (
            application.status == 5  # ApplicationStatus.REJECTED
            and not application.rejection_email_sent
        ):
            application.status = 9  # ApplicationStatus.REJECTION_PENDING
            application.save()
        elif application.status == 3:  # ApplicationStatus.CONFIRMED:
            if application.schedule_email_sent:
                application.status = 8  # ApplicationStatus.ASSIGNED
            else:
                application.status = 10  # ApplicationStatus.ASSIGNMENT_PENDING

            application.save()


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0042_alter_league_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Applied"),
                    (7, "Invitation Pending"),
                    (2, "Invited"),
                    (3, "Confirmed"),
                    (4, "Declined"),
                    (10, "Assignment Pending"),
                    (8, "Assigned"),
                    (9, "Rejection Pending"),
                    (5, "Rejected"),
                    (6, "Withdrawn"),
                ]
            ),
        ),
        migrations.RunPython(convert_statuses, elidable=True),
        migrations.RemoveField(
            model_name="application",
            name="invitation_email_sent",
        ),
        migrations.RemoveField(
            model_name="application",
            name="rejection_email_sent",
        ),
        migrations.RemoveField(
            model_name="application",
            name="schedule_email_sent",
        ),
        migrations.RemoveField(
            model_name="crewassignment",
            name="assignment_sent",
        ),
    ]
