# Generated by Django 5.2.3 on 2025-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stave",
            "0045_remove_applicationformtemplate_confirmed_email_template_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationformtemplate",
            name="intro_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
