# Generated by Django 5.2.3 on 2025-07-28 17:22

from django.db import migrations, models


def set_messagetemplate_names(apps, schema_editor):
    MessageTemplate = apps.get_model("stave", "MessageTemplate")

    if invitation_template := MessageTemplate.objects.filter(
        subject="Invitation to officiate {event.name}", name__isnull=True
    ).first():
        invitation_template.name = "Default Invitation Template"
        invitation_template.save()

    if rejection_template := MessageTemplate.objects.filter(
        subject="Your application to {event.name}", name__isnull=True
    ).first():
        rejection_template.name = "Default Rejection Template"
        rejection_template.save()

    if confirmation_template := MessageTemplate.objects.filter(
        subject="Confirmation to officiate {event.name}", name__isnull=True
    ).first():
        confirmation_template.name = "Default Rejection Template"
        confirmation_template.save()


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0046_alter_applicationformtemplate_intro_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RunPython(set_messagetemplate_names),
    ]
