# Generated by Django 5.2.3 on 2025-08-31 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0050_alter_rolegroup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
