# Generated by Django 5.2.3 on 2025-11-17 23:17

from django.db import migrations, models

import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0051_user_date_created"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE stave_applicationformtemplate_event_templates RENAME TO stave_applicationformtemplateassignment",
                    reverse_sql="ALTER TABLE stave_applicationformtemplateassignment RENAME TO stave_applicationfortemplate_event_templates",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ApplicationFormTemplateAssignment",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                primary_key=True,
                                editable=False,
                                serialize=False,
                            ),
                        ),
                        (
                            "eventtemplate",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="stave.EventTemplate",
                            ),
                        ),
                        (
                            "applicationformtemplate",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="stave.ApplicationFormTemplate",
                            ),
                        ),
                    ],
                    options={
                        "constraints": [
                            models.UniqueConstraint(
                                fields=["eventtemplate", "applicationformtemplate"],
                                name="stave_applicationformtemplate_event_templates_applicationformtemplate_id_eventtemplate_id_f2fba8ea_uniq",
                            )
                        ],
                    },
                ),
                migrations.AlterField(
                    model_name="applicationformtemplate",
                    name="event_templates",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="application_form_templates",
                        to="stave.EventTemplate",
                        through="stave.ApplicationFormTemplateAssignment",
                    ),
                ),
            ],
        ),
    ]
