# Generated by Django 5.2.3 on 2025-09-07 19:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0051_user_date_created"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE stave_applicationformtemplate_event_templates RENAME TO stave_applicationformtemplateassignment",
                    reverse_sql="ALTER TABLE stave_applicationformtemplateassignment RENAME TO stave_applicationformtemplate_event_templates",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ApplicationFormTemplateAssignment",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                default=uuid.uuid4,
                                editable=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "application_form_template",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="stave.ApplicationFormTemplate",
                            ),
                        ),
                        (
                            "event_template",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="stave.EventTemplate",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="applicationformtemplate",
                    name="event_templates",
                    field=models.ManyToManyField(
                        to="stave.EventTemplate",
                        through="stave.ApplicationFormTemplateAssignment",
                        blank=True,
                    ),
                ),
            ],
        ),
    ]
