# Generated by Django 5.2.3 on 2025-09-16 03:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0052_auto_20250907_1950"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationformtemplate",
            name="event_templates",
        ),
        migrations.AlterField(
            model_name="applicationformtemplateassignment",
            name="application_form_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_templates",
                to="stave.applicationformtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="applicationformtemplateassignment",
            name="event_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_form_templates",
                to="stave.eventtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="applicationformtemplateassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="nonexclusive",
            field=models.BooleanField(
                default=False,
                help_text="Nonexclusive Roles can be held simultaneously with another Role in the same Role Group.",
            ),
        ),
        migrations.AlterField(
            model_name="rolegroup",
            name="event_only",
            field=models.BooleanField(
                default=False,
                help_text="Event-only Role Groups are used to assign Event-wide Roles. They cannot be applied to Games.",
            ),
        ),
    ]
