# Generated by Django 5.2.3 on 2025-09-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stave",
            "0054_alter_applicationformtemplateassignment_application_form_template_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtemplate",
            name="application_form_templates",
            field=models.ManyToManyField(
                blank=True,
                through="stave.ApplicationFormTemplateAssignment",
                to="stave.applicationformtemplate",
            ),
        ),
    ]
