# Generated by Django 5.2.3 on 2025-11-25 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stave",
            "0055_alter_applicationformtemplateassignment_application_form_template_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewassignment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
