# Generated by Django 5.2.3 on 2025-09-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0055_eventtemplate_application_form_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationformtemplate",
            name="event_templates",
            field=models.ManyToManyField(
                blank=True,
                through="stave.ApplicationFormTemplateAssignment",
                to="stave.eventtemplate",
            ),
        ),
    ]
