# Generated by Django 5.2.3 on 2025-11-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0056_applicationformtemplate_event_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformtemplate',
            name='application_availability_kind',
            field=models.IntegerField(choices=[(1, 'Entire Event'), (2, 'By Day'), (3, 'By Game')], help_text='You can request availability at the level of the whole event, whole days, or by individual game. Single-game events must use Entire Event.', verbose_name='availability type'),
        ),
        migrations.AlterField(
            model_name='applicationformtemplate',
            name='application_kind',
            field=models.IntegerField(choices=[(1, 'Assign Only'), (2, 'Confirm then Assign')], help_text='Choose Assign Only to contact applicants only once, when the schedule is finalized. Choose Confirm then Assign to send acceptance messages first, then follow with a schedule.', verbose_name='application process'),
        ),
        migrations.AlterField(
            model_name='applicationformtemplate',
            name='intro_text',
            field=models.TextField(blank=True, help_text="Introduce the event to your applicants. You don't need to include dates or locations, because these are recorded on the event already. You can use Markdown to format this text.", null=True),
        ),
        migrations.AlterField(
            model_name='applicationformtemplate',
            name='requires_profile_fields',
            field=models.JSONField(blank=True, default=list, help_text="You can accept standard fields from the user's profile without requiring them to re-type their information. You always receive the Derby Name field."),
        ),
        migrations.AlterField(
            model_name='applicationformtemplate',
            name='role_groups',
            field=models.ManyToManyField(help_text='The role groups covered by this form. You can select any or all of the role groups assigned to the event. Each role group can appear on only one form.', to='stave.rolegroup'),
        ),
    ]
