# Generated by Django 5.2.3 on 2026-01-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0056_alter_applicationformtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mrda_recognized_official',
            field=models.CharField(blank=True, choices=[('Recognized', 'Recognized')], max_length=32, null=True, verbose_name='MRDA recognized official'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nso_certification_level',
            field=models.CharField(blank=True, choices=[('Recognized', 'Recognized'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3')], max_length=32, null=True, verbose_name='WFTDA NSO certification level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='so_certification_level',
            field=models.CharField(blank=True, choices=[('Recognized', 'Recognized'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3')], max_length=32, null=True, verbose_name='WFTDA SO certification level'),
        ),
    ]
