# Generated by Django 5.2.3 on 2025-11-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0057_alter_applicationformtemplate_application_availability_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='application_availability_kind',
            field=models.IntegerField(choices=[(1, 'Entire Event'), (2, 'By Day'), (3, 'By Game')], help_text='You can request availability at the level of the whole event, whole days, or by individual game. Single-game events must use Entire Event.', verbose_name='Availability type'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='application_kind',
            field=models.IntegerField(choices=[(1, 'Assign Only'), (2, 'Confirm then Assign')], help_text='Choose Assign Only to contact applicants only once, when the schedule is finalized. Choose Confirm then Assign to send acceptance messages first, then follow with a schedule.', verbose_name='Application process'),
        ),
        migrations.AlterField(
            model_name='applicationformtemplate',
            name='application_availability_kind',
            field=models.IntegerField(choices=[(1, 'Entire Event'), (2, 'By Day'), (3, 'By Game')], help_text='You can request availability at the level of the whole event, whole days, or by individual game. Single-game events must use Entire Event.', verbose_name='Availability type'),
        ),
        migrations.AlterField(
            model_name='applicationformtemplate',
            name='application_kind',
            field=models.IntegerField(choices=[(1, 'Assign Only'), (2, 'Confirm then Assign')], help_text='Choose Assign Only to contact applicants only once, when the schedule is finalized. Choose Confirm then Assign to send acceptance messages first, then follow with a schedule.', verbose_name='Application process'),
        ),
    ]
