# Generated by Django 5.2.3 on 2026-01-25 23:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0056_alter_applicationformtemplate_options_leaguegroup_and_more"),
        ("stave", "0057_user_mrda_recognized_official_and_more"),
    ]

    operations = []
