# Generated by Django 5.2.3 on 2026-02-03 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0056_alter_crewassignment_user"),
        ("stave", "0058_merge_20260125_2347"),
    ]

    operations = []
