# Generated by Django 5.2.11 on 2026-02-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0058_merge_20260125_2347"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
