# Generated by Django 5.2.11 on 2026-03-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0060_leagueuserinvitation_alter_event_banner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueuserinvitation",
            name="last_date_message_sent",
            field=models.DateField(blank=True, null=True),
        ),
    ]
