# Generated by Django 5.2.11 on 2026-03-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0061_leagueuserinvitation_last_date_message_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leagueuserinvitation",
            name="expiration_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="leagueuserinvitation",
            name="last_date_message_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
