# Generated by Django 5.2.13 on 2026-05-10 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0059_merge_20260203_0256"),
        ("stave", "0063_message_email_alter_message_user"),
    ]

    operations = []
