# Generated by Django 5.2.14 on 2026-07-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0064_alter_league_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
