# Generated by Django 5.2.16 on 2026-07-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stave', '0064_alter_league_time_zone'),
        ('stave', '0064_merge_20260510_1649'),
    ]

    operations = [
    ]
