# Generated by Django 5.2.14 on 2026-09-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0065_application_created_at_alter_league_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
