# Generated by Django 5.2.16 on 2026-07-19 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stave", "0065_application_created_at_alter_league_time_zone"),
        ("stave", "0065_merge_20260708_1827"),
    ]

    operations = []
